Feature/homework4
baraley/MagicBall pull request #5
Opened 2019-10-17 10:26 UTC by baraley

2019-10-17 12:19 UTC, yalantis-ios-school requested changes

2019-10-17 12:19 UTC, yalantis-ios-school commented on MagicBall/AppDelegate.swift
> +	private var persistentContainer: NSPersistentContainer = NSPersistentContainer(name: modelFileName)
стек не должен лежать в делегате приложения. для этого есть свой дб слой

2019-10-17 12:19 UTC, yalantis-ios-school commented on MagicBall/Core Data/Extensions/NSManagedObjectContext+Extension.swift
> +	func saveIfNeeds() {
выравнивание хромает

2019-10-17 12:19 UTC, yalantis-ios-school commented on MagicBall/Core Data/Models/ManagedAnswer+CoreDataClass.swift
> +        return NSFetchRequest<ManagedAnswer>(entityName: "Answer")
вместо строки стоит использовать String(describing: Answer.self), а еще лучше String(describing: ManagedAnswer.self)

2019-10-17 12:19 UTC, yalantis-ios-school commented on MagicBall/HistoryAnswersService.swift
> +//  HistoryAnswersService.swift
у тебя эти файлы лежат в руте проекта, нужно закинуть в соответствующие папки

2019-10-17 12:19 UTC, yalantis-ios-school commented on MagicBallModel.xcdatamodeld/MagicBallModel.xcdatamodel/contents
> +<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
этот файл вообще лежит вне проекта. положи его физически там же, где и в икскоде

2019-10-17 12:19 UTC, yalantis-ios-school commented on MagicBall/Core Data/Models/ManagedAnswerSet+CoreDataClass.swift
> +//  ManagedAnswerSet+CoreDataClass.swift
суффикс в названии файла лишний

2019-10-17 12:19 UTC, yalantis-ios-school commented on MagicBall/Core Data/Models/ManagedAnswerSet+CoreDataClass.swift
> +	public override func awakeFromInsert() {
для чего эта операция? ты если не заполняешь объект своими данными, то они у тебя невалидные

2019-10-17 12:19 UTC, yalantis-ios-school commented on MagicBall/Core Data/Models/ManagedAnswerSet+CoreDataClass.swift
> +		let answersArray: [ManagedAnswer] = answers.array.compactMap { $0 as? ManagedAnswer}
зачем тут конвертация сета в массив перед вызовом compactMap? она вообще ничего не делает, кроме как выполняет ненужные итерации

2019-10-17 12:19 UTC, yalantis-ios-school commented on MagicBall/Core Data/Models/ManagedAnswerSet+CoreDataClass.swift
> +		removeFromAnswers(answers)
а эта операция зачем?

2019-10-17 12:19 UTC, yalantis-ios-school commented on MagicBall/HistoryAnswerContentListViewModel.swift
> +extension HistoryAnswerContentListViewModel {
твоя VM слишком много на себя берет. она не должна заниматся ячейками. менеджинг представлений это прямая задача контроллера.

весь датасорс нужно перенести в контроллер.

2019-10-17 12:19 UTC, yalantis-ios-school commented on MagicBall/HistoryAnswerContentListViewModel.swift
> +	var listTitle: String = L10n.NavigationBar.Title.history
избыточная мутабельность и явный тип

2019-10-17 12:19 UTC, yalantis-ios-school commented on MagicBall/HistoryAnswerContentListViewModel.swift
> +	func createNewItem(with text: String) { }
зачем эти пустые методы тут?

2019-10-17 12:19 UTC, yalantis-ios-school commented on MagicBall/HistoryAnswersModel.swift
> +        weak var observer: HistoryAnswerModelObserver?
оверинжиниринг с этими обсерверами и доп прослойкой

переделывать уже не надо, но весь этот подход сложно поддерживать и требует потратить время на то, чтобы в нем разобраться

2019-10-17 12:19 UTC, yalantis-ios-school commented on MagicBall/Settings Tab/View Controllers/ContentListViewController.swift
> +			setupViewModel()
дважды вызов метода. в didSet он не срабатывает потому, что это начальное значение. нужно убрать

2019-10-17 12:19 UTC, yalantis-ios-school commented on MagicBall/Settings Tab/View Controllers/ContentListViewController.swift
> +protocol ContentListViewModel: UITableViewDataSource {
нет необходимости вводить протоколы для VM, т.к. они избыточны в общем случае

2019-10-17 12:22 UTC, yalantis-ios-school commented
в проекте непонятные прослойки в виде активных моделей, которые по сути выполняют роль моделей флоу и частично сервисов. такой подход тяжело поддерживать и уходит много времени на ревью

2019-10-21 10:15 UTC, baraley commented on MagicBall/Settings Tab/View Controllers/ContentListViewController.swift
> +protocol ContentListViewModel: UITableViewDataSource {
ContentListViewController у меня особенный, поэтому ему – нужны)
(особенность описал выше)

2019-10-21 10:15 UTC, baraley commented on MagicBall/HistoryAnswersModel.swift
> +        weak var observer: HistoryAnswerModelObserver?
Да, здесь обсерверы лишние. Поэтому Я их убрал.
Насчет дополнительной прослойки: отображение ответа на главном экране и ведение истории ответов это разные задачи, поэтому Я и выделил для них отдельные модели.

2019-10-21 10:18 UTC, baraley commented on MagicBall/HistoryAnswerContentListViewModel.swift
> +extension HistoryAnswerContentListViewModel {
ContentListViewController Я использую для отображения трех видов данных: истории ответов, списка наборов ответов, списка ответов из набора. ViewModel являющаяся UITableVIewDataSource это лучшее, что Я придумал для реализации данной функциональности. Если тебе известен вариант получше – буду рад о нем узнать)

2019-10-21 10:19 UTC, baraley commented on MagicBall/Core Data/Models/ManagedAnswerSet+CoreDataClass.swift
> +		removeFromAnswers(answers)
Чтобы обновляя список ответов в ManagedAnswerSet мне не нужно было искать в каких из ответов был изменен текст, какие были удалены, а какие добавлены. Я просто удаляю все старые ответы и сохраняю новые.

2019-10-22 11:05 UTC, baraley commented on MagicBall/Settings Tab/View Controllers/ContentListViewController.swift
> +protocol ContentListViewModel: UITableViewDataSource {
Причины данного решения описаны [выше](https://github.com/baraley/MagicBall/pull/5#discussion_r336940216)

2019-10-23 13:33 UTC, yalantis-ios-school commented on MagicBall/Core Data/Models/ManagedAnswerSet+CoreDataClass.swift
> +		for (index, answer) in answerSet.answers.enumerated() {
Тут можно просто без индексов добавлять по очереди все - результат будет один и тот же.

2019-10-24 11:24 UTC, merged